services:

  beneficiary-frontend:
    build: 
      context: ./beneficiary-frontend
      dockerfile: dockerfile.prod
    ports:
      - ${NEXT_PUBLIC_SERVER_PORT_FRONTEND}:${NEXT_PUBLIC_SERVER_PORT_FRONTEND}
    environment:
      - NODE_ENV=production
      - PORT=${NEXT_PUBLIC_SERVER_PORT_FRONTEND}
      - HOSTNAME=0.0.0.0
    restart: always

  login-hub-frontend:
    build: 
      context: ./login-hub-frontend
      dockerfile: dockerfile.prod
    ports:
      - ${LOGIN_FRONTEND_PORT}:${LOGIN_FRONTEND_PORT}
    environment:
      - NODE_ENV=production
      - PORT=${LOGIN_FRONTEND_PORT}
      - HOSTNAME=0.0.0.0
    restart: always