services:

  beneficiary-interface:
    build: 
      context: ./Beneficiary-Interface
      dockerfile: dockerfile.prod
    ports:
      - ${NEXT_PUBLIC_SERVER_PORT_FRONTEND}:${NEXT_PUBLIC_SERVER_PORT_FRONTEND}
    environment:
      - NODE_ENV=production
      - PORT=${NEXT_PUBLIC_SERVER_PORT_FRONTEND}
      - HOSTNAME=0.0.0.0
    restart: always

  login-hub-interface:
    build: 
      context: ./Login-Hub-Interface
      dockerfile: dockerfile.prod
    ports:
      - ${LOGIN_FRONTEND_PORT}:${LOGIN_FRONTEND_PORT}
    environment:
      - NODE_ENV=production
      - PORT=${LOGIN_FRONTEND_PORT}
      - HOSTNAME=0.0.0.0
    restart: always