services:

  beneficiary-frontend:
    build: ./beneficiary-frontend
    ports:
      - ${NEXT_PUBLIC_SERVER_PORT_FRONTEND}:${NEXT_PUBLIC_SERVER_PORT_FRONTEND}
    volumes:
      - ./beneficiary-frontend:/usr/app
      - /usr/app/node_modules
      - /usr/app/.next
    command: yarn dev -p ${NEXT_PUBLIC_SERVER_PORT_FRONTEND} --hostname 0.0.0.0
    restart: always

  login-hub-frontend:
    build: ./login-hub-frontend
    ports:
      - ${LOGIN_FRONTEND_PORT}:${LOGIN_FRONTEND_PORT}
    volumes:
      - ./login-hub-frontend:/usr/app
      - /usr/app/node_modules
      - /usr/app/.next
    command: yarn dev -p ${LOGIN_FRONTEND_PORT} --hostname 0.0.0.0
    restart: always